name: rgi
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >= 3.5
  - pip
  - biopython 1.78
  - filetype >= 1.0.0
  - pytest >= 3.0.0
  - pandas >= 0.15.0
  - matplotlib >= 2.1.2
  - seaborn >= 0.8.1
  - pyfaidx >= 0.5.4.1
  - pyahocorasick 1.4.0
  - pysam >= 0.16.0.1
  - beautifulsoup4 >= 4.9.3
  - requests 2.31.0
  - lxml >= 4.9.1
  - dask
  - blast 2.9.0
  - zlib
  - prodigal 2.6.3
  - pyrodigal >=2.0.0
  - diamond 0.8.36
  - oligoarrayaux 3.8
  - samtools 1.9
  - bamtools 2.5.1
  - bedtools >=2.28.0
  - bowtie2 >=2.3.4.3
  - bwa >=0.7.17
  - kma >=1.2.26s
