name: rgi
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - pip
  - biopython 1.78
  - filetype >= 1.0.0
  - pytest >= 3.0.0
  - pandas >= 0.15.0
  - matplotlib >= 2.1.2
  - seaborn >= 0.8.1
  - pyfaidx >= 0.5.4.1
  - pyahocorasick 1.4.0
  - pysam 0.22.1
  - beautifulsoup4 4.9.3
  - requests 2.24.0
  - lxml 5.3.0
  - blast 2.16.0
  - zlib
  - prodigal 2.6.3
  - pyrodigal >=3.0.0
  - diamond 0.8.36
  - oligoarrayaux 3.8
  - samtools 1.21
  - bamtools 2.5.2
  - bedtools >=2.31.1
  - bowtie2 >=2.5.4
  - bwa >=0.7.18
  - kma >=1.4.17
  - bioconda::jellyfish
  - dask
