name: rgi
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >= 3.5
  - pip
  - biopython 1.78
  - filetype >= 1.0.0
  - pytest >= 3.0.0
  - pyfaidx >= 0.5.4.1
  - pyahocorasick 1.4.0
  - pysam >= 0.16.0.1
  - beautifulsoup4
  - requests >= 2.0.0
  - lxml >= 4.0.0
  - pyrodigal >=2.0.0
  - dask
  - blast 2.9.0 # non-python/pip installable deps go below blast
  - jellyfish
  - zlib
  - prodigal 2.6.3
  - diamond 0.8.36
  - oligoarrayaux 3.8
  - samtools 1.9
  - bamtools >= 2.0.0
  - bedtools >= 2.28.0
  - kma >=1.2.26s
