{% set name = "rgi" %}
{% set version = "6.0.1" %}
{% set sha256 = "41892168b35d1385157a135f1b359d3686b5c4154b6e3cbd296b30b5126ad806" %}
{% set sha256database = "dd02b8c6d86fc1c3c83402a8985b765eeacd80c9f10d200138e775adc793fb08" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
    - url: https://github.com/arpcard/rgi/archive/{{ version }}.tar.gz
      sha256: {{ sha256 }}
    - url: https://card.mcmaster.ca/download/0/broadstreet-v3.2.5.tar.bz2
      sha256: {{ sha256database }}
      folder: card-data

build:
  noarch: python
  number: 1

requirements:
  host:
    - python >= 3.5
    - pip
    - biopython 1.78
    - filetype >= 1.0.0
    - pytest >= 3.0.0
    - pyfaidx >= 0.5.4.1
    - pyahocorasick 1.4.0
    - pysam >= 0.16.0.1
    - beautifulsoup4
    - requests >= 2.0.0
    - lxml >= 4.0.0
    - blast 2.9.0
    - zlib
    - prodigal 2.6.3
    - pyrodigal >=2.0.0
    - diamond 0.8.36
    - oligoarrayaux 3.8
    - samtools 1.9
    - bamtools >= 2.0.0
    - bedtools >= 2.28.0
    - kma >=1.2.26s
    - wget
  run:
    # RGI requires these exact versions of blast prodigal and diamond, or else --alignment_mode DIAMOND fails
    - python >= 3.5
    - pip
    - biopython 1.78
    - filetype >= 1.0.0
    - pytest >= 3.0.0
    - pyfaidx >= 0.5.4.1
    - pyahocorasick 1.4.0
    - pysam >= 0.16.0.1
    - beautifulsoup4
    - requests >= 2.0.0
    - lxml >= 4.0.0
    - blast 2.9.0
    - prodigal 2.6.3
    - pyrodigal >=2.0.0
    - diamond 0.8.36
    - oligoarrayaux 3.8
    - samtools 1.9
    - bamtools >= 2.0.0
    - bedtools >= 2.28.0
    - kma >=1.2.26s
    - wget
    - zlib
test:
  commands:
    - rgi database -v
    - rgi load -h
    - rgi auto_load -h
    - rgi main -h
    - rgi tab -h
    - rgi parser -h
    - rgi clean -h
    - rgi galaxy -h
    - rgi bwt -h
    - rgi kmer_build -h
    - rgi kmer_query -h
    - wget --quiet --output-document=homolog.fasta https://raw.githubusercontent.com/arpcard/rgi/master/tests/inputs/homolog.fasta | rgi main -i homolog.fasta -o output --debug -a diamond --clean


about:
  home: https://card.mcmaster.ca
  license: https://card.mcmaster.ca/about
  license_file: LICENSE
  summary: 'This tool provides a preliminary annotation of your DNA sequence(s) based upon the data available in The Comprehensive Antibiotic Resistance Database (CARD). Hits to genes tagged with Antibiotic Resistance ontology terms will be highlighted. As CARD expands to include more pathogens, genomes, plasmids, and ontology terms this tool will grow increasingly powerful in providing first-pass detection of antibiotic resistance associated genes. See license at CARD website'

extra:
  identifiers:
    - doi:10.1093/nar/gkz935
