# based on @rp3 bactopia workflow
name: Conda Build Test
on:
  release:
    types: [published]
jobs:
  conda-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout arpcard/rgi
        uses: actions/checkout@v2

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ""
          auto-activate-base: true

      - name: Build and Push 
        run: |
          conda update -c conda-forge conda
          conda install -c conda-forge -c bioconda anaconda-client conda-build conda-verify mamba 'python<3.10' 'numpy>=1.17'
          cd conda/recipe/ && mamba build -c conda-forge -c bioconda -c defaults --output-folder . . 
          anaconda upload --force ./noarch/*.tar.bz2
        env:
          ANACONDA_API_TOKEN: ${{ secrets.RGI_CONDA_BUILD }}
